# Generated by Django 6.0.4 on 2026-04-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
