# Generated by Django 6.0.4 on 2026-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_merchant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='created_at',
        ),
        migrations.AddField(
            model_name='merchant',
            name='balance_paise',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
